version: 1.0.{build}
image: Visual Studio 2019
before_build:
- ps: >-
    Write-Host "Building with appveyor.yml"
    
    Push-Location
    
    Set-Location $Env:APPVEYOR_BUILD_FOLDER
    
    .\ContinousIntegration\Build\Pre-Build.ps1
    
    Pop-Location
    
    nuget restore
build:
  verbosity: minimal